// Verified jump targets for EVERY cite (with PDF). Two stages, both honest:
//   1) a verbatim phrase from your sentence that appears in the PDF (exact).
//   2) otherwise: the source-PDF SENTENCE with the strongest content overlap
//      (bag-of-words); a verbatim fragment of it is marked.
// Nothing is guessed: the jump target is always verbatim from the PDF.
// Usage: node build_anchors.mjs   -> anchors.gen.js
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import { SOURCES } from "./claims.js";
import { CITECTX } from "./content.gen.js";

const here = dirname(fileURLToPath(import.meta.url));
const alnum = s => (s || "").toLowerCase().replace(/[^a-z0-9]/g, "");
const STOP = new Set(("the a an of to and or in on for with that this these those is are was were be been being by as at from into over under between within their its it they we our you your can could would should may might will not no only also more most than then so such each per one two three four five whole set same both other its is are we our this these has have had do does".split(" ")));
const words = s => s.toLowerCase().match(/[a-z][a-z0-9-]{2,}/g) || [];
const content = s => words(s).filter(w => !STOP.has(w));

const pdfCache = new Map();
async function loadPdf(pdf) {
  if (pdfCache.has(pdf)) return pdfCache.get(pdf);
  let raw = "";
  try {
    const doc = await getDocument({ data: new Uint8Array(readFileSync(join(here, pdf))) }).promise;
    for (let p = 1; p <= doc.numPages; p++)
      raw += " " + (await (await doc.getPage(p)).getTextContent()).items.map(i => i.str).join(" ");
  } catch {}
  raw = raw.replace(/-\s+/g, "").replace(/\s+/g, " ").trim();       // hyphenation + whitespace
  const flat = alnum(raw);
  const sents = raw.split(/(?<=[.!?])\s+(?=[A-Z(])/).filter(s => content(s).length >= 4);
  const val = { flat, sents: sents.map(s => ({ s, set: new Set(content(s)) })) };
  pdfCache.set(pdf, val);
  return val;
}

// verbatim candidates from the draft sentence (most distinctive first)
function verbatimCands(sentence) {
  const out = [];
  for (const m of sentence.matchAll(/[“"]([^”"]{10,})[”"]/g)) out.push(m[1]);
  const ws = sentence.replace(/[“”"()]/g, "").split(/\s+/).filter(Boolean);
  for (let n = 8; n >= 5; n--)
    for (let i = 0; i + n <= ws.length; i++) {
      const win = ws.slice(i, i + n);
      if (win.filter(w => !STOP.has(w.toLowerCase())).length < Math.ceil(n * 0.5)) continue;
      out.push(win.join(" "));
    }
  return out.filter(p => alnum(p).length >= 16);
}
// distinctive fragment of a source sentence (verbatim -> UI can highlight)
function fragmentOf(sent) {
  const ws = sent.replace(/\s+/g, " ").trim().split(" ");
  for (let start = 0; start < ws.length; start++) {
    for (let n = 10; n >= 6; n--) {
      const frag = ws.slice(start, start + n).join(" ");
      if (alnum(frag).length >= 24 && content(frag).length >= 3) return frag;
    }
  }
  return sent.length > 20 ? sent : null;
}

const anchors = {};
let exact = 0, overlap = 0, miss = 0, nopdf = 0;
const missList = [];
for (let i = 0; i < CITECTX.length; i++) {
  const ctx = CITECTX[i], src = SOURCES[ctx.key];
  if (!src?.pdf) { nopdf++; continue; }
  const { flat, sents } = await loadPdf(src.pdf);
  if (!flat) { miss++; missList.push(ctx.key); continue; }

  // stage 1: verbatim phrase
  let found = verbatimCands(ctx.sentence).find(c => flat.includes(alnum(c)));
  if (found) { anchors[i] = found; exact++; continue; }

  // stage 2: best overlapping source sentence
  const q = new Set(content(ctx.sentence));
  if (q.size >= 3) {
    let best = null, bestScore = 0;
    for (const cand of sents) {
      let shared = 0; for (const w of cand.set) if (q.has(w)) shared++;
      const score = shared / q.size;
      if (score > bestScore) { bestScore = score; best = cand.s; }
    }
    if (best && bestScore >= 0.34) {
      const frag = fragmentOf(best);
      if (frag && flat.includes(alnum(frag))) { anchors[i] = frag; overlap++; continue; }
    }
  }
  miss++; missList.push(ctx.key);
}

writeFileSync(join(here, "anchors.gen.js"),
  "// GENERATED by build_anchors.mjs — verified cite jump targets (verbatim from the PDF).\n" +
  `export const ANCHORS = ${JSON.stringify(anchors)};\n`);

const withPdf = exact + overlap + miss;
console.log(`Cites total: ${CITECTX.length} | without PDF (link only): ${nopdf}`);
console.log(`  with PDF: ${withPdf} → jump target: ${exact + overlap} (${Math.round(100 * (exact + overlap) / withPdf)}%)  [verbatim ${exact} · passage ${overlap}] | without anchor: ${miss}`);
if (missList.length) console.log("  without anchor (open p.1):", [...new Set(missList)].join(", "));
