// Evidence-reader data.
// SOURCES: every source cited in the drafts (pdf = local in pdfs/, otherwise url).
// CLAIMS: the 26 QA evidence items (needle = verbatim quote fragment, checked offline
//         against the PDF; they get a ✓/✗ verdict with hash invalidation).
// LOGCLAIMS: Fabian's already-verified refs.bib log evidence (jump target, no verdict).

export const SOURCES = {
  // QA sources
  guo2024llmma:   { pdf: "pdfs/guo2024llmma.pdf",   label: "Guo et al. 2024 · IJCAI" },
  tran2025collab: { pdf: "pdfs/tran2025collab.pdf", label: "Tran et al. 2025 · arXiv:2501.06322" },
  xi2025rise:     { pdf: "pdfs/xi2025rise.pdf",     label: "Xi et al. · SCIS 2025 / arXiv:2309.07864" },
  chen2024mas:    { pdf: "pdfs/chen2024mas.pdf",    label: "Chen et al. 2024 · arXiv:2412.17481",
                    url: "https://arxiv.org/html/2412.17481v2" },
  smit2024mad:    { pdf: "pdfs/smit2024mad.pdf",    label: "Smit et al. 2024 · ICML" },
  cemri2025mast:  { pdf: "pdfs/cemri2025mast.pdf",  label: "Cemri et al. 2025 · NeurIPS" },
  trankiela2026:  { pdf: "pdfs/trankiela2026.pdf",  label: "Tran & Kiela 2026 · arXiv:2604.02460" },
  tian2025beyond: { pdf: "pdfs/tian2025beyond.pdf", label: "Tian et al. 2025 · arXiv:2509.23537" },
  wang2025agenttaxo: { pdf: null, label: "Wang et al. 2025 · AgentTaxo (OpenReview, bot wall)",
                    url: "https://openreview.net/forum?id=0iLbiYYIpC" },
  // further cited sources with a free PDF
  wu2024:            { pdf: "pdfs/wu2024.pdf",            label: "Wu et al. 2024 · AutoGen · COLM" },
  tang2025complexity:{ pdf: "pdfs/tang2025complexity.pdf",label: "Tang et al. 2025 · arXiv:2510.04311" },
  kim2025:           { pdf: "pdfs/kim2025.pdf",           label: "Kim et al. 2025 · arXiv:2512.08296" },
  madaan2023selfrefine:{ pdf: "pdfs/madaan2023selfrefine.pdf", label: "Madaan et al. 2023 · Self-Refine · NeurIPS" },
  huang2023selfcorrect:{ pdf: "pdfs/huang2023selfcorrect.pdf", label: "Huang et al. 2024 · ICLR" },
  alvarado2025repetitions:{ pdf: "pdfs/alvarado2025repetitions.pdf", label: "Alvarado et al. 2025 · arXiv:2509.24086" },
  blackwell2024reproducible:{ pdf: "pdfs/blackwell2024reproducible.pdf", label: "Blackwell et al. 2024 · arXiv:2410.03492" },
  bouthillier2021variance:{ pdf: "pdfs/bouthillier2021variance.pdf", label: "Bouthillier et al. 2021 · MLSys" },
  tewel2024consistory:{ pdf: "pdfs/tewel2024consistory.pdf", label: "Tewel et al. 2024 · ConsiStory · TOG" },
  yang2024idea2img:  { pdf: "pdfs/yang2024idea2img.pdf",  label: "Yang et al. 2024 · Idea2Img · ECCV" },
  chen2026:          { pdf: "pdfs/chen2026.pdf",          label: "Chen et al. 2026 · arXiv:2601.04703" },
  lin2025:           { pdf: "pdfs/lin2025.pdf",           label: "Lin et al. 2025 · arXiv:2505.21116" },
  salim2026:         { pdf: "pdfs/salim2026.pdf",         label: "Salim et al. 2026 · Tokenomics · arXiv" },
  zhang2025:         { pdf: "pdfs/zhang2025.pdf",         label: "Zhang et al. 2025 · Cut the Crap · ICLR" },
  yan2025beyond:     { pdf: "pdfs/yan2025beyond.pdf",     label: "Yan et al. 2025 · arXiv:2502.14321" },
  wang2025diver:     { pdf: "pdfs/wang2025diver.pdf",     label: "Wang et al. 2025 · arXiv:2508.18739" },
  koltsov2026tiqa:   { pdf: "pdfs/koltsov2026tiqa.pdf",   label: "Koltsov et al. 2026 · TIQA · arXiv" },
  tripathi2025:      { pdf: "pdfs/tripathi2025.pdf",      label: "Tripathi et al. 2025 · COLM" },
  ku2024viescore:    { pdf: "pdfs/ku2024viescore.pdf",    label: "Ku et al. 2024 · VIEScore · ACL" },
  liu2024interleaved:{ pdf: "pdfs/liu2024interleaved.pdf",label: "Liu et al. 2024 · InterleavedEval · EMNLP" },
  lu2025textimageplan:{ pdf: "pdfs/lu2025textimageplan.pdf", label: "Lu et al. 2025 · Findings ACL" },
  zeng2025s2mad:     { pdf: "pdfs/zeng2025s2mad.pdf",     label: "Zeng et al. 2025 · S2-MAD · NAACL" },
  wang2025mimo:      { pdf: "pdfs/wang2025mimo.pdf",      label: "Wang et al. 2025 · EMNLP Industry" },
  callisonburch2007meta:{ pdf: "pdfs/callisonburch2007meta.pdf", label: "Callison-Burch et al. 2007 · WMT" },
  novikova2018rankme:{ pdf: "pdfs/novikova2018rankme.pdf",label: "Novikova et al. 2018 · RankME · NAACL" },
  artstein2008:      { pdf: "pdfs/artstein2008.pdf",      label: "Artstein & Poesio 2008 · CL" },
  fang2020spaq:      { pdf: "pdfs/fang2020spaq.pdf",      label: "Fang et al. 2020 · SPAQ · CVPR" },
  ye2025justice:     { pdf: "pdfs/ye2025justice.pdf",     label: "Ye et al. 2025 · ICLR" },
  // without a free PDF: opens the source page
  hartmann2025:      { pdf: null, url: "https://doi.org/10.1016/j.ijresmar.2024.09.002", label: "Hartmann et al. 2025 · IJRM" },
  lin2023:           { pdf: null, url: "https://doi.org/10.1145/3581783.3611930", label: "Lin et al. 2023 · AutoPoster · ACM MM" },
  ding2025muses:     { pdf: null, url: "https://doi.org/10.1609/aaai.v39i3.32280", label: "Ding et al. 2025 · MUSES · AAAI" },
  lin2024vqascore:   { pdf: null, url: "https://doi.org/10.1007/978-3-031-72673-6_20", label: "Lin et al. 2024 · VQAScore · ECCV" },
  tangUnreal2025:    { pdf: null, url: "https://scholar.google.com/scholar?q=UnrealLLM+Controllable+Interactable+3D+Scene+Generation", label: "Tang et al. 2025 · UnrealLLM · Findings ACL" },
  vanderlee2021:     { pdf: null, url: "https://doi.org/10.1016/j.csl.2020.101151", label: "van der Lee et al. 2021 · CS&L" },
  tomkins2017:       { pdf: null, url: "https://doi.org/10.1073/pnas.1707323114", label: "Tomkins et al. 2017 · PNAS" },
  legge2011printsize:{ pdf: null, url: "https://doi.org/10.1167/11.5.8", label: "Legge & Bigelow 2011 · J. Vision" },
  meta2026adsguide:  { pdf: null, url: "https://www.facebook.com/business/ads-guide/", label: "Meta Ads Guide (Web)" },
  meta2026igapi:     { pdf: null, url: "https://developers.facebook.com/docs/instagram-api/reference/ig-user/media", label: "Instagram Graph API (Web)" },
  openai2026seed:    { pdf: null, url: "https://developers.openai.com/cookbook/examples/reproducible_outputs_with_the_seed_parameter", label: "OpenAI Seed Docs (Web)" },
  anthropic2026api:  { pdf: null, url: "https://platform.claude.com/docs/en/api/messages", label: "Anthropic Messages API (Web)" },
  anthropic2024agents:{ pdf: null, url: "https://www.anthropic.com/engineering/building-effective-agents", label: "Anthropic · Building Effective Agents (Web)" },
  belch2021advertising:{ pdf: null, url: "https://books.google.com/books?vid=ISBN9781260259315", label: "Belch & Belch 2021 · Book" },
  dibia2025:         { pdf: null, url: "https://multiagentbook.com/", label: "Dibia 2025 · Designing Multi-Agent Systems · Book" },
};

export const CLAIMS = {
  "guo-whymas":       { key: "guo2024llmma",   needle: "diverse agent profiles, inter-agent interactions" },
  "guo-profiling":    { key: "guo2024llmma",   needle: "Pre-defined, Model-Generated, and Data-Derived" },
  "guo-paradigms":    { key: "guo2024llmma",   needle: "a consensus or a more refined solution" },
  "guo-topology4":    { key: "guo2024llmma",   needle: "central agent coordinating the system" },
  "tran-5dims":       { key: "tran2025collab", needle: "actors, types, structures, strategies" },
  "tran-rolebased":   { key: "tran2025collab", needle: "error propagation by modularizing task distribution" },
  "tran-central":     { key: "tran2025collab", needle: "managing, controlling, and coordinating" },
  "tran-staticdynamic": { key: "tran2025collab", needle: "predefined rules to establish collaboration channels" },
  "xi-taxonomy":      { key: "xi2025rise",     needle: "Adversarial Interaction for Advancement" },
  "xi-ordered":       { key: "xi2025rise",     needle: "focus on the outputs from upstream" },
  "xi-amplify":       { key: "xi2025rise",     needle: "amplify minor hallucinations indefinitely" },
  "xi-debatefail":    { key: "xi2025rise",     needle: "requiring high-quality responses and accurate decision" },
  "s2412-three":      { key: "chen2024mas",    needle: "serial problem solvers at different stages" },
  "s2412-default":    { key: "chen2024mas",    needle: "multiple agents working together will be well suited" },
  "s2412-decomp":     { key: "chen2024mas",    needle: "split tasks into subtasks" },
  "mad-notbetter":    { key: "smit2024mad",    needle: "do not reliably outperform other proposed prompting strategies" },
  "mad-verifiable":   { key: "smit2024mad",    needle: "MedQA, PubMedQA and MMLU" },
  "mad-threshold":    { key: "smit2024mad",    needle: "additional computing does not guarantee better results" },
  "mast-minimal":     { key: "cemri2025mast",  needle: "performance gains on popular benchmarks are often minimal" },
  "mast-failrates":   { key: "cemri2025mast",  needle: "41% to 86.7%" },
  "mast-taxonomy":    { key: "cemri2025mast",  needle: "inter-agent misalignment" },
  "tk-budget":        { key: "trankiela2026",  needle: "statistically indistinguishable from the best" },
  "tk-confound":      { key: "trankiela2026",  needle: "confounded by increased test-time computation" },
  "orch-numbers":     { key: "tian2025beyond", needle: "GPQA-Diamond" },
  "orch-nosig":       { key: "tian2025beyond", needle: "McNemar" },
  "agenttaxo-roles":  { key: "wang2025agenttaxo", needle: "Planner, Reasoner, and Verifier" },
};

// Fabian's log evidence (already checked by him against the source; jump target, no verdict)
export const LOGCLAIMS = {
  "cb07-ranking":     { key: "callisonburch2007meta", needle: "might be false" },
  "rankme-setup2":    { key: "novikova2018rankme",    needle: "very low levels" },
  "spaq-attrib":      { key: "fang2020spaq",          needle: "0.784" },
  "consistory-setsim":{ key: "tewel2024consistory",   needle: "DreamSim" },
  "blackwell-temp0":  { key: "blackwell2024reproducible", needle: "temperature" },
  "openai-seed":      { key: "openai2026seed" },
  "anthropic-temp0":  { key: "anthropic2026api" },
  "anthropic-patterns":{ key: "anthropic2024agents" },
};
