// Takes the LLM results (workflow_out.json), checks each quote VERBATIM
// against the real source PDF and writes only verified jump targets to
// anchors.gen.js. Non-verbatim -> longest verbatim substring as a fallback.
// Unsupported cites -> anchor_audit.md (weak quotes you want to check).
// Usage: node verify_and_build_anchors.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import { SOURCES } from "./claims.js";

const here = dirname(fileURLToPath(import.meta.url));
const tasks = JSON.parse(readFileSync(join(here, "anchor_tasks.json"), "utf8"));
const out = JSON.parse(readFileSync(join(here, "workflow_out.json"), "utf8"));
const results = out.results || out;
const alnum = s => (s || "").toLowerCase().replace(/[^a-z0-9]/g, "");

const flatCache = new Map();
async function flatOf(pdf) {
  if (flatCache.has(pdf)) return flatCache.get(pdf);
  let raw = "";
  try {
    const doc = await getDocument({ data: new Uint8Array(readFileSync(join(here, pdf))) }).promise;
    for (let p = 1; p <= doc.numPages; p++)
      raw += " " + (await (await doc.getPage(p)).getTextContent()).items.map(i => i.str).join(" ");
  } catch {}
  const flat = alnum(raw.replace(/-\s+/g, ""));
  flatCache.set(pdf, flat);
  return flat;
}
// longest verbatim substring of the quote that appears in the PDF (word window)
function longestVerbatim(quote, flat) {
  const ws = quote.split(/\s+/).filter(Boolean);
  for (let n = ws.length; n >= 5; n--)
    for (let i = 0; i + n <= ws.length; i++) {
      const frag = ws.slice(i, i + n).join(" ");
      if (alnum(frag).length >= 24 && flat.includes(alnum(frag))) return frag;
    }
  return null;
}

const anchors = {};
const audit = [];
let exact = 0, recovered = 0, unverified = 0, weak = 0;
for (const r of results) {
  const t = tasks[r.i];
  if (!t) continue;
  const rec = { key: t.key, statement: t.sentence, supported: r.supported, quote: r.quote || "", why: r.why || "" };
  if (r.supported === "no" || !r.quote) { rec.status = "no-evidence"; weak++; audit.push(rec); continue; }
  const flat = await flatOf(SOURCES[t.key].pdf);
  let needle = null;
  if (flat.includes(alnum(r.quote))) { needle = r.quote; exact++; rec.status = "verbatim"; }
  else {
    const frag = longestVerbatim(r.quote, flat);
    if (frag) { needle = frag; recovered++; rec.status = "verbatim-substring"; rec.used = frag; }
    else { unverified++; rec.status = "non-verbatim (discarded)"; }
  }
  if (r.supported === "partial") { rec.status += " · partial only"; }
  if (needle) for (const cix of t.cix) anchors[cix] = needle;
  else weak++;
  audit.push(rec);
}

writeFileSync(join(here, "anchors.gen.js"),
  "// GENERATED by verify_and_build_anchors.mjs — verified cite jump targets (verbatim from the PDF).\n" +
  `export const ANCHORS = ${JSON.stringify(anchors)};\n`);

// audit report: what you should look at
const weakOnes = audit.filter(a => a.status.startsWith("no-evidence") || a.status.includes("partial") || a.status.includes("discarded"));
const md = ["# Cite Evidence Audit\n",
  `Of ${results.length} cites checked: ${exact} verbatim-supported, ${recovered} via verbatim substring, ${unverified} not verifiable, ${weak} without evidence/partial.\n`,
  `**${weakOnes.length} cites worth a look** (no clear evidence in the excerpts — possibly a weak quote or evidence outside the excerpts):\n`,
  ...weakOnes.map(a => `- **${a.key}** [${a.status}] — Statement: “${a.statement.slice(0, 110)}…”${a.why ? `\n  - LLM: ${a.why}` : ""}`)];
writeFileSync(join(here, "anchor_audit.md"), md.join("\n"));

const total = Object.keys(anchors).length;
console.log(`Jump targets written (cix): ${total} | verbatim ${exact} · substring ${recovered} · discarded ${unverified} · without evidence ${weak}`);
console.log(`Audit: anchor_audit.md (${weakOnes.length} cites to review)`);
